/**
 * External evidence source registry — describe before integrating.
 */

import type { ExternalSourceDescriptor } from "./types.ts";

export const EXTERNAL_CONTEXT_REGISTRY: ExternalSourceDescriptor[] = [
  {
    id: "open_meteo_archive",
    category: "weather",
    source: "Open-Meteo Historical Weather API (ERA5 reanalysis)",
    url: "https://archive-api.open-meteo.com/v1/archive",
    license: "Data CC BY 4.0; hosted free API is non-commercial (self-host AGPLv3 for production commercial)",
    costClass: 1,
    temporalCoverage: "1940–present daily/hourly",
    geographicCoverage: "global; NAC uses pinned branch coordinates",
    cachingPolicy: "immutable historical days cached forever by branch+date range",
    reliability: "high",
    freshness: "reanalysis lag ~2–5 days",
    supportedQueryType: "aligned period weather comparison",
    status: "LIVE",
    notes: "No API key. Do not use customer-open-meteo paid endpoint. Cache-first.",
  },
  {
    id: "ksa_holiday_seed",
    category: "saudi_public_holidays",
    source: "NAC trusted KSA holiday registry + Gregorian fixed dates",
    url: "https://www.my.gov.sa/",
    license: "public calendar facts (static seed)",
    costClass: 0,
    temporalCoverage: "seeded 2024–2027 Gregorian fixed + named Islamic windows",
    geographicCoverage: "Saudi Arabia (national)",
    cachingPolicy: "permanent — immutable calendar facts",
    reliability: "high",
    freshness: "static until year table updated",
    supportedQueryType: "holiday overlap with business period",
    status: "SEEDED",
    notes: "Founding Day / National Day fixed; Eid/Ramadan from temporal seed table.",
  },
  {
    id: "nac_islamic_calendar_seed",
    category: "islamic_calendar",
    source: "Existing NAC temporal seed (Ramadan / Eid)",
    url: "internal:temporalService.SEEDED_NAMED_PERIODS",
    license: "internal seed",
    costClass: 0,
    temporalCoverage: "2025–2026 named windows",
    geographicCoverage: "KSA operations",
    cachingPolicy: "permanent seed",
    reliability: "high",
    freshness: "updated with NAC event engine",
    supportedQueryType: "Ramadan/Eid overlap",
    status: "SEEDED",
    notes: "Reuses existing event engine; does not scrape Hijri converters.",
  },
  {
    id: "ksa_school_calendar_seed",
    category: "school_calendar",
    source: "Seeded typical KSA academic year windows (MOE-style)",
    url: "https://moe.gov.sa/",
    license: "public academic-calendar facts (approximate windows)",
    costClass: 0,
    temporalCoverage: "2025–2026 academic year typical breaks",
    geographicCoverage: "Saudi public school system (national typical)",
    cachingPolicy: "permanent until seed revision",
    reliability: "medium",
    freshness: "annual seed",
    supportedQueryType: "school-holiday overlap vs trading window",
    status: "SEEDED",
    notes: "Not a live MOE feed. Windows are typical and labelled medium quality.",
  },
  {
    id: "sports_static_calendar",
    category: "sports_events",
    source: "Seeded major football tournament windows (FIFA published)",
    url: "https://www.fifa.com/",
    license: "public tournament dates",
    costClass: 0,
    temporalCoverage: "major 2025–2026 windows",
    geographicCoverage: "global / KSA demand relevance",
    cachingPolicy: "permanent for historical tournament windows",
    reliability: "high",
    freshness: "static tournament dates",
    supportedQueryType: "fixture-window overlap; weekend football difference",
    status: "SEEDED",
    notes: "No paid sports API. Match-level SPL fixtures not licensed — overlap uses tournament windows.",
  },
  {
    id: "local_events_bounded",
    category: "local_events",
    source: "Bounded Wikimedia summary lookup (optional class 2) + cache",
    url: "https://en.wikipedia.org/api/rest_v1/",
    license: "CC BY-SA 4.0 (Wikipedia)",
    costClass: 2,
    temporalCoverage: "ad hoc cached discoveries",
    geographicCoverage: "Khobar / Dhahran / Dammam",
    cachingPolicy: "cache discoveries by location+period",
    reliability: "low",
    freshness: "on-demand",
    supportedQueryType: "major local event presence, not exhaustive scrape",
    status: "LIVE",
    notes: "Not a giant scraper. Used only when selected and material.",
  },
  {
    id: "traffic_founder_blocked",
    category: "traffic",
    source: "None — TomTom / Google / HERE historical congestion are paid",
    url: "n/a",
    license: "n/a",
    costClass: 3,
    temporalCoverage: "n/a",
    geographicCoverage: "Grand House Open Mall approaches",
    cachingPolicy: "n/a",
    reliability: "unavailable",
    freshness: "n/a",
    supportedQueryType: "historical congestion / closures",
    status: "UNAVAILABLE_IN_FOUNDER_FREE_MODE",
    notes: "OSM has no durable historical congestion. Do not recreate TomTom.",
  },
  {
    id: "web_research_fallback",
    category: "web_research_fallback",
    source: "Not a general web search engine",
    url: "n/a",
    license: "n/a",
    costClass: 2,
    temporalCoverage: "n/a",
    geographicCoverage: "n/a",
    cachingPolicy: "n/a",
    reliability: "low",
    freshness: "n/a",
    supportedQueryType: "last-resort bounded lookup via Wikipedia only",
    status: "LIVE",
    notes: "Must not become unrestricted browsing. Same Wikipedia bound as local events.",
  },
];

export function getExternalSource(id: string): ExternalSourceDescriptor | null {
  return EXTERNAL_CONTEXT_REGISTRY.find((s) => s.id === id) || null;
}

export function founderBlockedCategories(): string[] {
  return EXTERNAL_CONTEXT_REGISTRY.filter((s) => s.status === "UNAVAILABLE_IN_FOUNDER_FREE_MODE" || s.costClass === 3)
    .map((s) => s.category);
}
