/**
 * Inventory Truth Engine contracts.
 * Missing / unavailable / partial are never coerced to zero.
 */

export const SOURCE_SYSTEM = Object.freeze({
  NAC_INVENTORY: "nac_inventory",
  CANONICAL_COMMERCE: "canonical_commerce",
  FOODICS_SALES: "foodics_sales_items",
  SUPPLIER_CATALOGUE: "inventory_supplier_catalogue_items",
  COST_STATE: "inventory_ingredient_cost_state",
  COST_HISTORY: "inventory_ingredient_cost_history",
  MOVEMENTS: "inventory_movements",
  STOCK_COUNTS: "inventory_stock_counts",
});

/** Ledger quantity field. Graph expansion uses quantityBase internally; cost must not. */
export const THEORETICAL_LEDGER_CONTRACT = Object.freeze({
  quantityField: "quantityTheoreticallyConsumed",
});

export function theoreticalConsumedQuantity(row) {
  const value = row?.[THEORETICAL_LEDGER_CONTRACT.quantityField];
  if (value == null || value === "") return null;
  return value;
}

export const CONVERSION_STATUS = Object.freeze({
  EXACT: "EXACT",
  CONVERTED: "CONVERTED",
  MISSING_CONVERSION: "MISSING_CONVERSION",
  INCOMPATIBLE: "INCOMPATIBLE",
  UNKNOWN: "UNKNOWN",
});

export const IDENTITY_CONFIDENCE = Object.freeze({
  CANONICAL_ID: "CANONICAL_ID",
  VERIFIED_SKU: "VERIFIED_SKU",
  AMBIGUOUS: "AMBIGUOUS",
  LEGACY: "LEGACY",
  OCR_PLACEHOLDER: "OCR_PLACEHOLDER",
});

export const COST_CLASS = Object.freeze({
  VALID: "VALID_COST",
  VERIFIED_ZERO: "VERIFIED_ZERO_COST",
  NO_PURCHASE_HISTORY: "NO_PURCHASE_HISTORY",
  PURCHASE_ITEM_NOT_LINKED: "PURCHASE_ITEM_NOT_LINKED",
  LATEST_PURCHASE_PRICE_MISSING: "LATEST_PURCHASE_PRICE_MISSING",
  INGREDIENT_COST_NULL: "INGREDIENT_COST_NULL",
  SUB_RECIPE_DERIVED_COST_NOT_CALCULATED: "SUB_RECIPE_DERIVED_COST_NOT_CALCULATED",
  UOM_CONVERSION_BLOCKS_COST: "UOM_CONVERSION_BLOCKS_COST",
  SUPPLIER_MAPPING_MISSING: "SUPPLIER_MAPPING_MISSING",
  LEGACY_SOURCE: "LEGACY_SOURCE",
  OCR_PLACEHOLDER: "OCR_PLACEHOLDER",
  UNKNOWN: "UNKNOWN",
});

export const COST_METHOD = Object.freeze({
  WEIGHTED_AVERAGE: "weighted_average",
  LAST_PURCHASE: "last_purchase",
  VERIFIED_ZERO: "verified_zero",
  UNAVAILABLE: "unavailable",
});

export const ACTUAL_COVERAGE = Object.freeze({
  AVAILABLE: "AVAILABLE",
  PARTIAL: "PARTIAL",
  UNAVAILABLE: "UNAVAILABLE",
});

export const VARIANCE_STATUS = Object.freeze({
  VALID: "VALID",
  NOT_COMPUTABLE: "VARIANCE_NOT_COMPUTABLE",
  ZERO_THEORETICAL_DENOMINATOR: "ZERO_THEORETICAL_DENOMINATOR",
  UOM_INCOMPATIBLE: "UOM_INCOMPATIBLE",
});

export const YIELD_STATUS = Object.freeze({
  SOURCE_BACKED: "SOURCE_BACKED",
  UNKNOWN: "YIELD_UNKNOWN",
});

export const GRAPH_STATUS = Object.freeze({
  OK: "OK",
  CIRCULAR: "CIRCULAR_RECIPE",
  MISSING_RECIPE: "MISSING_RECIPE",
  MISSING_SUB_RECIPE: "MISSING_SUB_RECIPE",
  MULTIPLE_ACTIVE_VERSIONS: "MULTIPLE_ACTIVE_VERSIONS",
  INACTIVE_VERSION: "INACTIVE_VERSION",
  LEGACY_RECIPE: "LEGACY_RECIPE_CONTAMINATION",
  MISSING_QUANTITY: "MISSING_QUANTITY",
  INVALID_QUANTITY: "INVALID_QUANTITY",
  AMBIGUOUS_RECIPE: "AMBIGUOUS_RECIPE_IDENTITY",
  INVALID_SUBRECIPE_VERSION_OR_UNIT: "INVALID_SUBRECIPE_VERSION_OR_UNIT",
});

export const VARIANCE_REASON = Object.freeze({
  RECIPE_QUANTITY_SUSPECT: "RECIPE_QUANTITY_SUSPECT",
  MISSING_RECIPE: "MISSING_RECIPE",
  MISSING_SUB_RECIPE: "MISSING_SUB_RECIPE",
  UOM_CONVERSION_MISSING: "UOM_CONVERSION_MISSING",
  COST_MISSING: "COST_MISSING",
  PRODUCTION_DEDUCTION_MISSING: "PRODUCTION_DEDUCTION_MISSING",
  SALES_MAPPING_GAP: "SALES_MAPPING_GAP",
  STOCK_COUNT_GAP: "STOCK_COUNT_GAP",
  PURCHASE_MAPPING_GAP: "PURCHASE_MAPPING_GAP",
  DUPLICATE_INGREDIENT_IDENTITY: "DUPLICATE_INGREDIENT_IDENTITY",
  LEGACY_RECIPE_CONTAMINATION: "LEGACY_RECIPE_CONTAMINATION",
  ACTUAL_SOURCE_PARTIAL: "ACTUAL_SOURCE_PARTIAL",
  YIELD_UNKNOWN: "YIELD_UNKNOWN",
  WASTE_NOT_CAPTURED: "WASTE_NOT_CAPTURED",
  TRANSFER_COVERAGE_GAP: "TRANSFER_COVERAGE_GAP",
  ADJUSTMENT_COVERAGE_GAP: "ADJUSTMENT_COVERAGE_GAP",
});

export const READINESS = Object.freeze({
  READY: "READY",
  PARTIAL: "PARTIAL",
  BLOCKED: "BLOCKED",
  UNAVAILABLE: "UNAVAILABLE",
});

/** Recommended sign: actual − theoretical. Positive = more recorded than sales require. */
export const VARIANCE_SIGN = "actual_minus_theoretical";
