export const PACK_STATUS = Object.freeze({
  OK: "OK",
  PACK_CONVERSION_REQUIRED: "PACK_CONVERSION_REQUIRED",
  PACK_REVIEW_REQUIRED: "PACK_REVIEW_REQUIRED",
  IMPOSSIBLE_UNIT_CONVERSION: "IMPOSSIBLE_UNIT_CONVERSION",
});

export const MAPPING_STATE = Object.freeze({
  AUTO_MATCHED: "AUTO_MATCHED",
  SUGGESTED: "SUGGESTED",
  NEEDS_REVIEW: "NEEDS_REVIEW",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  AMBIGUOUS: "AMBIGUOUS",
});

export const DUPLICATE_STATE = Object.freeze({
  NEW: "NEW",
  POSSIBLE_DUPLICATE: "POSSIBLE_DUPLICATE",
  CONFIRMED_DUPLICATE: "CONFIRMED_DUPLICATE",
  SUPERSEDED: "SUPERSEDED",
  APPROVED: "APPROVED",
});

export const PROCUREMENT_CATEGORY = Object.freeze({
  FOOD: "FOOD",
  BEVERAGE: "BEVERAGE",
  PACKAGING: "PACKAGING",
  CLEANING: "CLEANING",
  OPERATING_SUPPLIES: "OPERATING_SUPPLIES",
  EQUIPMENT: "EQUIPMENT",
  OTHER: "OTHER",
});

export const RECIPE_COST_STATUS = Object.freeze({
  COMPLETE: "COMPLETE",
  PARTIAL_COST: "PARTIAL_COST",
  UNKNOWN: "UNKNOWN",
});

export const COST_VIEW = Object.freeze({
  LATEST_PURCHASE_COST: "LATEST_PURCHASE_COST",
  WEIGHTED_AVERAGE_PURCHASE_COST: "WEIGHTED_AVERAGE_PURCHASE_COST",
  ROLLING_AVERAGE_COST: "ROLLING_AVERAGE_COST",
  LAST_APPROVED_COST: "LAST_APPROVED_COST",
  CURRENT_RECIPE_COST: "CURRENT_RECIPE_COST",
});

export const COST_PROVENANCE = Object.freeze({
  VERIFIED_INVOICE: "VERIFIED_INVOICE",
  APPROVED_MAPPING: "APPROVED_MAPPING",
  EXPLICIT_PACK: "EXPLICIT_PACK",
  EXACT_UOM_CONVERSION: "EXACT_UOM_CONVERSION",
  OCR_LOW_CONFIDENCE: "OCR_LOW_CONFIDENCE",
  PACK_ASSUMED: "PACK_ASSUMED",
  MAPPING_SUGGESTED: "MAPPING_SUGGESTED",
  UNKNOWN: "UNKNOWN",
});

export const ANOMALY = Object.freeze({
  PRICE_SPIKE: "PRICE_SPIKE",
  PRICE_DROP: "PRICE_DROP",
  PACK_SIZE_CHANGED: "PACK_SIZE_CHANGED",
  UOM_CHANGED: "UOM_CHANGED",
  SUPPLIER_PRODUCT_CHANGED: "SUPPLIER_PRODUCT_CHANGED",
  UNKNOWN_INGREDIENT: "UNKNOWN_INGREDIENT",
  AMBIGUOUS_MAPPING: "AMBIGUOUS_MAPPING",
  DUPLICATE_INVOICE: "DUPLICATE_INVOICE",
  MISSING_PRICE: "MISSING_PRICE",
  MISSING_QUANTITY: "MISSING_QUANTITY",
  VAT_MISMATCH: "VAT_MISMATCH",
  LINE_TOTAL_MISMATCH: "LINE_TOTAL_MISMATCH",
  INVOICE_TOTAL_MISMATCH: "INVOICE_TOTAL_MISMATCH",
  PACK_CONVERSION_REQUIRED: "PACK_CONVERSION_REQUIRED",
  IMPOSSIBLE_UNIT_CONVERSION: "IMPOSSIBLE_UNIT_CONVERSION",
});

export const INVOICE_WORKFLOW = Object.freeze({
  UPLOADED: "uploaded",
  EXTRACTED: "extracted",
  NEEDS_REVIEW: "needs_review",
  READY_TO_APPROVE: "ready_to_approve",
  APPROVED: "approved",
  POSTED: "posted",
  REJECTED: "rejected",
  DUPLICATE: "duplicate",
});

export function isRecipeCostCategory(category) {
  return category === PROCUREMENT_CATEGORY.FOOD || category === PROCUREMENT_CATEGORY.BEVERAGE;
}

export function canAffectCanonicalCost(mappingState) {
  return mappingState === MAPPING_STATE.AUTO_MATCHED || mappingState === MAPPING_STATE.APPROVED;
}
